version: '3'

services:
  web:
    image: node:14-alpine
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm start"

