CREATE USER user1 IDENTIFIED BY 'password1';
CREATE USER user2 IDENTIFIED BY 'password2';

GRANT ALL PRIVILEGES ON mydatabase.* TO user1;
GRANT SELECT, INSERT, UPDATE, DELETE ON mydatabase.* TO user2;

SELECT User FROM mysql.user;
SHOW DATABASES;

ALTER USER user1 IDENTIFIED BY 'newpassword1';
ALTER USER user2 IDENTIFIED BY 'newpassword2';
