CREATE USER user1 WITH PASSWORD 'password1';
CREATE USER user2 WITH PASSWORD 'password2';
CREATE DATABASE mydatabase;

GRANT ALL PRIVILEGES ON DATABASE mydatabase TO user1;
GRANT CONNECT ON DATABASE mydatabase TO user2;
GRANT USAGE ON SCHEMA public TO user2;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO user2;

SELECT usename FROM pg_user;
SELECT datname FROM pg_database;

ALTER USER user1 WITH PASSWORD 'newpassword1';
ALTER USER user2 WITH PASSWORD 'newpassword2';

